project:
  type: website

website:
  title: "self halt"
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - posts.qmd
    right:
      - books.qmd

format:
  html:
    theme: litera
    css: styles.css
    toc: true



